package org.idempiere.model;

import com.landawn.abacus.annotation.Column;
import com.landawn.abacus.annotation.Id;
import com.landawn.abacus.annotation.Table;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Inventory Line Material Allocation entity - M_InventoryLineMA table.
 * Inventory line attribute set instance allocation.
 */
@Data
@SuperBuilder
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@Table("M_InventoryLineMA")
public class InventoryLineMA extends BaseEntity {

    @Id
    @Column("M_InventoryLineMA_ID")
    private Integer mInventoryLineMaId;

    @Column("M_InventoryLine_ID")
    private Integer mInventoryLineId;

    @Column("M_AttributeSetInstance_ID")
    private Integer mAttributeSetInstanceId;

    @Column("MovementQty")
    private BigDecimal movementQty;

    @Column("DateMaterialPolicy")
    private LocalDateTime dateMaterialPolicy;

    @Column("IsAutoGenerated")
    private String isAutoGenerated;
}
